# Generated by Django 5.2 on 2026-06-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('sport', 'Sport'), ('tech', 'Texnologiya'), ('politics', 'Siyasat'), ('education', 'Bilim')], default='tech', max_length=20),
        ),
    ]
