# Generated by Django 5.2 on 2026-06-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_updated_at_alter_news_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(default='Admin', max_length=100),
        ),
    ]
